name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install project dependencies
        run: npm install

      - name: Build React project
        run: npm run build

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Log build directory size
        run: du -sh dist

      - name: Deploy to Shared Hosting using FTP
        env:
          FTP_USERNAME: "u504134335.videosroom"
          FTP_PASSWORD: "GnewP@ss4131#2024"
          FTP_HOST: "ftp://153.92.11.151"
        run: |
          cd dist
          echo "Starting FTP upload at $(date)"
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R -x .git/ ./"
          echo "Finished FTP upload at $(date)"

      - name: Clean up
        run: echo "Clean up step"
